### ISSUE TITLE
check output reference file

### ISSUE THREAD

**Issue by aremazeilles** [STEPbySTEPproj/Protocol_biomechanics#16]
I fixed the windows - unix end of line issue, but some inconsistencies remain:

Have a look at the [build process](https://github.com/STEPbySTEPproj/Protocol_biomechanics/runs/2677123624), which launch your program, and compare the generated output and the one stored in the reference file.

It fails with the following item:
```
Traceback (most recent call last):
  File "test_docker_call.py", line 154, in test_call_docker
    self.assertListEqual(lines_generated, lines_groundtruth, msg="File {} differs".format(filename))
AssertionError: Lists differ: ['type: vector\n', 'value: [-7.30179, 9.55601, 2.66103, 3.0556]\n'] != ['type: vector\n', 'value: [-7.30179, 9.55601, 2.42899, 2.62426]\n']

First differing element 1:
'value: [-7.30179, 9.55601, 2.66103, 3.0556]\n'
'value: [-7.30179, 9.55601, 2.42899, 2.62426]\n'

- ['type: vector\n', 'value: [-7.30179, 9.55601, 2.66103, 3.0556]\n']
?                                                   ^^^^^^^^^^^

+ ['type: vector\n', 'value: [-7.30179, 9.55601, 2.42899, 2.62426]\n']
?                                                +++++++++   ^^^
 : File descending_ankle_left_angle.yml differs

```

Can you check this on your machine? 
If needed, could you update the reference output files?
In the CI process please focus on the BUILD job. That is where the generated output and the reference ones are compared.

I can handle later on the issue with the yaml file format. But the content is up to you

**Comment by aremazeilles** [comment]
It is not. You have to click on the red cross, and click on details for the push on master build. That one should be turned to green.
There you can reach the [error](https://github.com/STEPbySTEPproj/Protocol_biomechanics/runs/2682667133)

if you scroll up a bit, it complains because of:

```
File "/home/pi_runner/pi_algo/pi_algo/run_pi_mocap_metrics.py", line 13, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```
I´ll switch to linux and investigate this.

**Comment by aremazeilles** [comment]
Fixed, I added `matplotlib` into the dependencies, event though it seems you are not using it for metric computation.
